CovidManager/CovidManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api', include('myapi.urls')),
]

CovidManager/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.statistic_ru, name='ru'),
    path('world', views.statistic_world, name='world'),
    # path('world?country=<str>', views.statistic_world, name='world_'),

]

CovidManager/myapi/urls.py
from django.urls import path
from . import views

from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()

app_name = "myapi"
urlpatterns = [
    path('/', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

CovidManager/main/models.py
from django.db import models

# Create your models here.

CovidManager/myapi/models.py
from django.db import models

# Create your models here.

CovidManager/main/views.py
# from django.shortcuts import render
from django.shortcuts import render, redirect

from django.http import HttpResponseRedirect, Http404, HttpRequest, HttpResponseForbidden
import requests

import urllib.request, json

# Create your views here.

"countriys 800count"
"https://api.apify.com/v2/key-value-stores/tVaYRsPHLjNdNBu7S/records/LATEST?disableRedirect=true&desc=true"

"https://api.apify.com/v2/datasets/5JO5GL1h8Qv1CnG0m/items?format=json&limit=10&offset=0&desc=true"

month_list = ['янв', 'фев', 'мар', 'апр', 'мая', 'июн',
              'июл', 'авг', 'сен', 'окт', 'ноя', 'дек']


def statistic_context(request: HttpRequest, urls_api: tuple):
    nn = 2
    # historycal
    with requests.get(urls_api[0]) as res:
        print(res)
        if res.status_code == 200:
            data = res.json()
            if "timeline" in data:
                tl = data["timeline"]
            else:
                tl = data
            count = len(tl.get("cases")) // nn
            cases = list(tl["cases"].values())
            cases_list = [cases[i] for i in range(len(cases)) if i % nn == 0]
            deaths = list(tl["deaths"].values())
            deaths_list = [deaths[i] for i in range(len(deaths)) if i % nn == 0]
            recovered = list(tl["recovered"].values())
            recovered_list = [recovered[i] for i in range(len(recovered)) if i % nn == 0]
            dates = list(tl["cases"].keys())
            dataf = lambda d: d[1] + " " + month_list[int(d[0]) - 1] + " " + d[2] + "г."
            dates_list = [dataf(dates[i].split("/")) for i in range(len(dates)) if i % nn == 0]

            print(data)
        else:
            count = 0
            cases_list = deaths_list = recovered_list = dates_list = 0

    # strings statistic
    with requests.get(urls_api[1]) as res:
        if res.status_code == 200:
            data = res.json()
            numf = lambda x: '{0:,}'.format(x).replace(',', ' ')
            cases = numf(data["cases"])
            todayCases = numf(data["todayCases"])
            deaths = numf(data["deaths"])
            recovered = numf(data["recovered"])
            tests = ">{},{} млн".format(data["tests"] // 1000000, data["tests"] % 1000000 // 100000)
        else:
            cases = 0
            todayCases = 0
            deaths = 0
            recovered = 0
            tests = 0

    # vaccine
    with requests.get(urls_api[2]) as res:
        if res.status_code == 200:
            data = res.json()
            if "timeline" in data:
                tl = data["timeline"]
            else:
                tl = data
            count2 = len(tl) // nn
            tests_list = list(tl.values())
            tests_list = [tests_list[i] for i in range(len(tests_list)) if i % nn == 0]
            tests_list = [0] * (count - count2) + tests_list
        else:
            count2 = 0
            tests_list = []
    print(len(tests_list), count2, count)

    return {"cases_list": cases_list, "deaths_list": deaths_list,
            "recovered_list": recovered_list, "dates_list": dates_list,
            "cases": cases, "deaths": deaths,
            "recovered": recovered, "tests_list": tests_list,
            "tests": tests, "todayCases": todayCases,
            }


def statistic_ru(request: HttpRequest):
    urls_api = (
        'https://disease.sh/v3/covid-19/historical/ru?lastdays=all',
        'https://disease.sh/v3/covid-19/countries/ru?strict=true',
        "https://disease.sh/v3/covid-19/vaccine/coverage/countries/ru?lastdays=all&fullData=false"
    )

    if request.method == 'GET':
        region = request.GET.get('region', None)
    elif request.method == "POST":
        region = request.POST['region'],
    else:
        region = None
    if not region:
        context = statistic_context(request, urls_api)
        context["country_title"] = "России"

    return render(request, 'main/InfoRussian.html', context=context)


def statistic_world(request: HttpRequest, country=None):
    urls_api = (
        'https://disease.sh/v3/covid-19/historical/all?lastdays=all',
        'https://disease.sh/v3/covid-19/all?strict=true',
        "https://disease.sh/v3/covid-19/vaccine/coverage/?lastdays=all&fullData=false"
    )
    if request.method == 'GET':
        country = request.GET.get('country', None)
    elif request.method == "POST":
        country = request.POST['country']
    else:
        country = None
    if country == "Russia":
        return redirect("main:ru")
    if country and country != "World":
        urls_api = (
            f'https://disease.sh/v3/covid-19/historical/{country}?lastdays=all',
            f'https://disease.sh/v3/covid-19/countries/{country}?strict=true',
            f"https://disease.sh/v3/covid-19/vaccine/coverage/countries/{country}?lastdays=all&fullData=false"
            )
        print(urls_api)
    context = statistic_context(request, urls_api)
    context["country_title"] = country or "мире"
    context["country"] = country
    context["countries_list"] = ["World"] + get_countries_list()

    return render(request, 'main/InfoWorld.html', context=context)


def get_countries_list():
    url = "https://disease.sh/v3/covid-19/continents"
    with requests.get(url) as req:
        data = req.json()
        lst = [ctr for contin in data for ctr in contin["countries"] if " " not in ctr]
        print(lst)
    return lst

CovidManager/myapi/views.py
from django.shortcuts import render

# Create your views here.

CovidManager/main/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}MySite{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Verdana&display=swap" rel="stylesheet"/>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">


    <script src="{% static 'main/js/script.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"></script>
</head>

<body style="background-color: rgb(238, 240, 242)">
<header class="p-3 mb-3 fixed-top sticky-top p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <div class="container d-flex flex-column flex-md-row align-items-center ">


        <h3 class="my-0 mr-md-auto font-weight-large"><a href="/" class="badge badge-dark" style="box-shadow: none;"><img
                src="{% static 'images/Head.png' %}" alt="" class="navbar-left " style="max-width:100px"> </a></h3>
            <div class="dropdown p-2 header-link">
                <a class="nav-link dropdown-toggle p-2 text-dark header-link" href="#" id="navbarDropdownMenuLink"
                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Статистика в
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item p-2 text-dark header-link" href="/">России</a>
                  <a class="dropdown-item p-2 text-dark header-link" href="/world">мире</a>
                  <a class="dropdown-item p-2 text-dark header-link" href="/">моём регионе</a>
                </div>
            </div>
        <nav class="my-2 my-md-0 mr-md-3">
<!--            <a class="p-2 text-dark header-link" href="/">Статистика по России</a>-->
<!--            <a class="p-2 text-dark header-link" href="/world">Статистика по миру</a>-->
            <a class="p-2 text-dark header-link" href="#">Последние новости</a>
            <a class="p-2 text-dark header-link" href="#">Пользовательские блоги</a>
<!--            <a class="p-2 text-dark header-link" href="#">Помощь</a>-->
        </nav>
<!--        <form class="col-12 col-lg-auto ">-->
<!--            <input type="search" class="form-control" placeholder="Поиск..." aria-label="Search">-->
<!--        </form>-->
    </div>
</header>

<div class="container bg-white">

    {% block content %} {% endblock %}
</div>

<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>
</html>

CovidManager/main/templates/main/InfoRussian.html
{% extends 'main/Statistic.html' %}

{% load static %}

{% block title %} COVID-19 в России {% endblock %}

{% block content-choice %}
{% endblock %}

CovidManager/main/templates/main/InfoWorld.html
{% extends 'main/Statistic.html' %}

{% load static %}

{% block title %} COVID-19 в мире {% endblock %}

{% block content-choice %}
<div class="container-fluid form-choice">
    <form method="POST" class="" action="{% url 'main:world' %}">
        {% csrf_token %}
        <div class="form-row align-items-bottom justify-content-end">
            <div class="col-sm-8 my-1">
                <select class="form-control" id="country" name="country">
                    {% for ctr_name in countries_list %}
                      <option {% if ctr_name == country %} selected {% endif %}>{{ctr_name}}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Уточнить страну</button>

        </div>
    </form>
</div>
{% endblock %}

CovidManager/main/templates/main/Statistic.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Последние статьи {% endblock %}

{% block content %}


<div class="container">
    <div class="title-statistic">Статистика по COVID-19 <br><span></span>в {{country_title}}</div>
  <div class="row">
    <div class="col">
      <img class="img-fluid" src="{% static 'images/statistic.png' %}">
    </div>
    <div class="col">

            <div class="stat-text">
                <div class="value-s" style="color:#15803D">{{recovered}}</div>
                <div class="value-text-label" style="color:#14532D">Человек выздоровело</div>

                <div class="stat-text-margin">
                    <div class="value-s" style="color:#991B1B">{{cases}}</div>
                    <div class="value-text-label" style="color:#991B1B">Выявлено случаев</div>
                    <div class="stat-text-margin">
                        <div class="value-s" style="color:#C2410C">{{todayCases}}</div>
                        <div class="value-text-label" style="color:#7C2D12">Выявлено случаев<br>за последние сутки</div>
                    </div>
                </div>
            </div>




            <div class="stat-text">
                <div class="value-s bg" style="color:#0284C7">{{tests}}</div>
                <div class="value-text-label" style="color:#0C4A6E">Проведено тестов</div>
                <div class="stat-text-margin">
                    <div class="value-s" style="color:#525252">{{deaths}}</div>
                    <div class="value-text-label" style="color:#000000">Человек умерло</div>
                </div>
            </div>


      {% block content-choice %} {% endblock %}
    </div>

  </div>
</div>



<canvas id="myChart" width="100%" height="50"></canvas>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        responsive: true,
        labels: {{dates_list|safe}},
        datasets: [
        {
            label: 'выздоровело',
            data: {{ recovered_list }},
            borderColor: '#84CC16',
            radius:0,
            borderWidth: 3,
            yAxisID: 'y2',
        },
        {
            label: 'выявлено',
            data: {{ cases_list }},
            borderColor: '#991B1B',
            borderWidth: 3,
            radius:0,
            yAxisID: 'y2',

        },
        {
            label: 'умерло',
            data: {{ deaths_list }},
            borderColor: '#18181B',
            radius:0,

            borderWidth: 3,
            yAxisID: 'y2',
        },

        {
            label: 'вакцинаций COVID-19',
            data: {{ tests_list }},
            borderColor: '#1D4ED8',
            radius:0,
            borderWidth: 3,
            yAxisID: 'y3',
        },

        ]
    },

    options: {
        responsive: true,
        plugins: {
          title: {
            display: true,
            text: 'Количество COVID-19 в {{country_title}} за всё время пандемии'
          },
        },
        interaction: {
          intersect: false,
        },
        scales: {
            y2: {
                            min: 0,

                type: 'linear',
                offset: true,
                position: 'left',
                stack: 'demo',
                stackWeight: 1,
                grid: {
                  borderColor: 'rgba(53, 53, 53, 1)'
                  },
           y3: {
                min: 0,
                type: 'linear',
                offset: true,
                position: 'left',
                stack: 'demo',
                stackWeight: 1,
                grid: {
                  borderColor: '#1D4ED8'
                  }
                  },

            y: {
                            min: 0,

                type: 'linear',
                offset: true,
                position: 'left',
                stack: 'demo',
                stackWeight: 1,
                grid: {
                  borderColor: 'rgba(206, 22, 22, 1)'
                  },
            },
            x: {
                stacked: true,
                text: 'Дата',
                title: {
                  display: true
                }
            },
            grid: {
                drawOnChartArea: false, // only want the grid lines for one axis to show up
            },


            },





    }
},


});




</script>
{% endblock %}

CovidManager/main/templates/main/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Последние статьи {% endblock %}

{% block content %}
   <canvas id="myChart" width="100%" height="50"></canvas>
   <script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        },
        {
            label: '# of Votes',
            data: [1, 9, 13, 4, 12, 13],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },

    options: {
        scales: {
            y: {
                beginAtZero: true,
                stacked: true
            },
            x: {
        stacked: true,
            },
        }
    },


});
</script>
{% endblock %}